// <auto-generated />
namespace AngularJSAuthentication.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class tkn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tkn));
        
        string IMigrationMetadata.Id
        {
            get { return "201606180751288_tkn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
